"use strict";
var __cov_aLPlanUg_hyKDywMcjfb_g = (Function('return this'))();
if (!__cov_aLPlanUg_hyKDywMcjfb_g.__coverage__) { __cov_aLPlanUg_hyKDywMcjfb_g.__coverage__ = {}; }
__cov_aLPlanUg_hyKDywMcjfb_g = __cov_aLPlanUg_hyKDywMcjfb_g.__coverage__;
if (!(__cov_aLPlanUg_hyKDywMcjfb_g['lib\\syncModel\\index.js'])) {
   __cov_aLPlanUg_hyKDywMcjfb_g['lib\\syncModel\\index.js'] = {"path":"lib\\syncModel\\index.js","s":{"1":0,"2":1,"3":0,"4":0,"5":0,"6":1,"7":0,"8":0,"9":0,"10":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"syncModel","line":5,"loc":{"start":{"line":5,"column":0},"end":{"line":5,"column":24}}},"2":{"name":"(anonymous_2)","line":9,"loc":{"start":{"line":9,"column":36},"end":{"line":9,"column":47}}},"3":{"name":"initConfig","line":13,"loc":{"start":{"line":13,"column":0},"end":{"line":13,"column":25}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":3,"column":27}},"2":{"start":{"line":5,"column":0},"end":{"line":7,"column":1}},"3":{"start":{"line":6,"column":1},"end":{"line":6,"column":28}},"4":{"start":{"line":9,"column":0},"end":{"line":11,"column":2}},"5":{"start":{"line":10,"column":1},"end":{"line":10,"column":17}},"6":{"start":{"line":13,"column":0},"end":{"line":20,"column":1}},"7":{"start":{"line":15,"column":1},"end":{"line":17,"column":2}},"8":{"start":{"line":16,"column":2},"end":{"line":16,"column":38}},"9":{"start":{"line":19,"column":1},"end":{"line":19,"column":12}},"10":{"start":{"line":22,"column":0},"end":{"line":22,"column":27}}},"branchMap":{"1":{"line":15,"type":"if","locations":[{"start":{"line":15,"column":1},"end":{"line":15,"column":1}},{"start":{"line":15,"column":1},"end":{"line":15,"column":1}}]}}};
}
__cov_aLPlanUg_hyKDywMcjfb_g = __cov_aLPlanUg_hyKDywMcjfb_g['lib\\syncModel\\index.js'];
__cov_aLPlanUg_hyKDywMcjfb_g.s['1']++;let util=require('util');function syncModel(cfg){__cov_aLPlanUg_hyKDywMcjfb_g.f['1']++;__cov_aLPlanUg_hyKDywMcjfb_g.s['3']++;this.cfg=initConfig(cfg);}__cov_aLPlanUg_hyKDywMcjfb_g.s['4']++;syncModel.prototype.syncGetConfig=function(){__cov_aLPlanUg_hyKDywMcjfb_g.f['2']++;__cov_aLPlanUg_hyKDywMcjfb_g.s['5']++;return this.cfg;};function initConfig(cfg){__cov_aLPlanUg_hyKDywMcjfb_g.f['3']++;__cov_aLPlanUg_hyKDywMcjfb_g.s['7']++;if(util.isNullOrUndefined(cfg)){__cov_aLPlanUg_hyKDywMcjfb_g.b['1'][0]++;__cov_aLPlanUg_hyKDywMcjfb_g.s['8']++;throw new Error('cfg not defined!');}else{__cov_aLPlanUg_hyKDywMcjfb_g.b['1'][1]++;}__cov_aLPlanUg_hyKDywMcjfb_g.s['9']++;return cfg;}__cov_aLPlanUg_hyKDywMcjfb_g.s['10']++;module.exports=syncModel;
