"use strict";
var __cov_NzfZ2qPnZ0CDRjKiU9uNqg = (Function('return this'))();
if (!__cov_NzfZ2qPnZ0CDRjKiU9uNqg.__coverage__) { __cov_NzfZ2qPnZ0CDRjKiU9uNqg.__coverage__ = {}; }
__cov_NzfZ2qPnZ0CDRjKiU9uNqg = __cov_NzfZ2qPnZ0CDRjKiU9uNqg.__coverage__;
if (!(__cov_NzfZ2qPnZ0CDRjKiU9uNqg['lib\\asyncModel\\index.js'])) {
   __cov_NzfZ2qPnZ0CDRjKiU9uNqg['lib\\asyncModel\\index.js'] = {"path":"lib\\asyncModel\\index.js","s":{"1":0,"2":0,"3":1,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":1,"12":0,"13":0,"14":0,"15":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0,"4":0},"fnMap":{"1":{"name":"SyncModel","line":6,"loc":{"start":{"line":6,"column":0},"end":{"line":6,"column":24}}},"2":{"name":"(anonymous_2)","line":13,"loc":{"start":{"line":13,"column":37},"end":{"line":13,"column":48}}},"3":{"name":"(anonymous_3)","line":17,"loc":{"start":{"line":17,"column":40},"end":{"line":17,"column":59}}},"4":{"name":"initConfig","line":21,"loc":{"start":{"line":21,"column":0},"end":{"line":21,"column":25}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":3,"column":50}},"2":{"start":{"line":4,"column":0},"end":{"line":4,"column":27}},"3":{"start":{"line":6,"column":0},"end":{"line":9,"column":1}},"4":{"start":{"line":7,"column":1},"end":{"line":7,"column":25}},"5":{"start":{"line":8,"column":1},"end":{"line":8,"column":28}},"6":{"start":{"line":11,"column":0},"end":{"line":11,"column":39}},"7":{"start":{"line":13,"column":0},"end":{"line":15,"column":2}},"8":{"start":{"line":14,"column":1},"end":{"line":14,"column":35}},"9":{"start":{"line":17,"column":0},"end":{"line":19,"column":2}},"10":{"start":{"line":18,"column":1},"end":{"line":18,"column":20}},"11":{"start":{"line":21,"column":0},"end":{"line":27,"column":1}},"12":{"start":{"line":22,"column":1},"end":{"line":24,"column":2}},"13":{"start":{"line":23,"column":2},"end":{"line":23,"column":38}},"14":{"start":{"line":26,"column":1},"end":{"line":26,"column":12}},"15":{"start":{"line":29,"column":0},"end":{"line":29,"column":27}}},"branchMap":{"1":{"line":22,"type":"if","locations":[{"start":{"line":22,"column":1},"end":{"line":22,"column":1}},{"start":{"line":22,"column":1},"end":{"line":22,"column":1}}]}}};
}
__cov_NzfZ2qPnZ0CDRjKiU9uNqg = __cov_NzfZ2qPnZ0CDRjKiU9uNqg['lib\\asyncModel\\index.js'];
__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['1']++;let EventEmitter=require('events').EventEmitter;__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['2']++;let util=require('util');function SyncModel(cfg){__cov_NzfZ2qPnZ0CDRjKiU9uNqg.f['1']++;__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['4']++;EventEmitter.call(this);__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['5']++;this.cfg=initConfig(cfg);}__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['6']++;util.inherits(SyncModel,EventEmitter);__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['7']++;SyncModel.prototype.asyncGetConfig=function(){__cov_NzfZ2qPnZ0CDRjKiU9uNqg.f['2']++;__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['8']++;this.emit('get config',this.cfg);};__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['9']++;SyncModel.prototype.callbackGetConfig=function(callback){__cov_NzfZ2qPnZ0CDRjKiU9uNqg.f['3']++;__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['10']++;callback(this.cfg);};function initConfig(cfg){__cov_NzfZ2qPnZ0CDRjKiU9uNqg.f['4']++;__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['12']++;if(util.isNullOrUndefined(cfg)){__cov_NzfZ2qPnZ0CDRjKiU9uNqg.b['1'][0]++;__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['13']++;throw new Error('cfg not defined!');}else{__cov_NzfZ2qPnZ0CDRjKiU9uNqg.b['1'][1]++;}__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['14']++;return cfg;}__cov_NzfZ2qPnZ0CDRjKiU9uNqg.s['15']++;module.exports=SyncModel;
